name: PlayerReports
version: 1.0
author: moderator_man
main: me.moderator_man.pr.PlayerReports
commands:
    report:
        description: Report a player to the staff.
        usage: /report <username> <message>
    resolve:
        description: Mark a report as resolved.
        usage: /resolve <id>
    reports:
        description: List all reports.
        usage: /reports [resolved]
    flushreports:
        description: Flush all resolved reports.
        usage: /flushreports